name: Update Random Fun Fact

on:
  schedule:
    - cron: "0 5 * * *" # Every day at 5AM UTC
  workflow_dispatch: # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install jq
        run: sudo apt-get install jq

      - name: Pick a random fun fact
        id: fact
        run: |
          FACT=$(jq -r '.[]' fun-facts.json | shuf -n 1)
          echo "FACT=$FACT" >> "$GITHUB_ENV"

      - name: Replace fun fact in README
        run: |
          awk -v fact="$FACT" '
          BEGIN { print = 1 }
          /<!--FUN_FACT-->/ { print = 1; print; print fact; next }
          /<!--\/FUN_FACT-->/ { print = 0 }
          print
          ' README.md > temp.md
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update fun fact"
          git push
